export default ActionTypes = {

    POST_LISTING_REQUEST: "POST_LISTING_REQUEST",
    POST_LISTING_SUCCESS: "POST_LISTING_SUCCESS",
    POST_LISTING_FAILURE: "POST_LISTING_FAILURE",

    LOAD_LISTINGS_REQUEST: "LOAD_LISTINGS_REQUEST",
    LOAD_LISTINGS_SUCCESS: "LOAD_LISTINGS_SUCCESS",
    LOAD_LISTINGS_FAILURE: "LOAD_LISTINGS_FAILURE",


    // Items
    LOAD_ITEMS_REQUEST: "LOAD_ITEMS_REQUEST",
    LOAD_ITEMS_SUCCESS: "LOAD_ITEMS_SUCCESS",
    LOAD_ITEMS_FAILURE: "LOAD_ITEMS_FAILURE",


    LOAD_USERS_REQUEST: "LOAD_USERS_REQUEST",
    LOAD_USERS_SUCCESS: "LOAD_USERS_SUCCESS",
    LOAD_USERS_FAILURE: "LOAD_USERS_FAILURE",

}

